name = "gms_basis_reader"
version = "0.1.0"
license = "license"
author = "JorgeGV"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2025, JorgeGV"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

