name = "metalquicha"
version = "0.1.0"
license = "license"
author = "JorgeGV"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2025, JorgeGV"
[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]
[build]
auto-executables = false
auto-tests = true
auto-examples = false
module-naming = false
external-modules = ["mpi_f08", "mpi"]
[[executable]]
name = "metalquicha"
source-dir = "app"
main = "main.f90"
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
pic = { git = "https://github.com/JorgeG94/pic.git", branch = "main"}
pic-mpi = { git = "https://github.com/JorgeG94/pic-mpi.git", branch = "main"}
pic-blas = { git = "https://github.com/JorgeG94/pic-blas.git", branch = "main"}
tblite = { git = "https://github.com/JorgeG94/tblite", branch = "main"}
test-drive.git = "https://github.com/JorgeG94/test-drive"
[extra.fortitude.check]
select = ["C", "E", "S"]
ignore = ["C003", "C072", "S212", "S082", "C043", "C122"]
line-length = 132
